---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: inventory-catalog
  description: webservices used to search ressources in the inventory
  tags:
    - java
    - quarkus
  links:
    - url: https://www.gravitee.io/
      title: gravitee configuration page
  annotations:
    gitlab.com/project-id: "250833"
    newrelic.com/dashboard-guid: NDA4ODYwMHxWSVp8REFTSEJPQVJEfGRhOjIzOTQzNQ
    backstage.io/adr-location: adrs
    backstage.io/techdocs-ref: dir:../../../
spec:
  type: service
  lifecycle: production
  providesApis: [inventory-api]
  consumesApis: [messaging-kafka-connector-api]
  dependsOn: [resource:default/inventory-db]
  owner: team-inventory-1
  system: Inventory
